config/routes.rb
Laguna::Application.routes.draw do

  resources :doc_categories

  resources :ecnreview_forms

  resources :ecndocuments do
    member do 
      get 'print'
    end
  end

  resources :approvals

  resources :customer_infos do
    member do
      get 'get_th_pn'
      get 'get_suggestions'
    end
  end

  resources :ecnsignatures

  resources :ecnpositions

  resources :ecnusers do
    member do
      get 'edit_profile'
      put 'update_profile'
    end
  end
  
  match 'login' => "Login#index"
  match 'logout' => "Login#destroy"
  
  match 'admin/login' => "Admin#index"
  match 'admin/logout' => "Admin#destroy"
  match 'admin' => "Admin#index"

  root :to => "ecndocuments#index"

end

app/views/admin/index.html.erb
<center>
<table>
	<tr><td align="center"><img src="/images/thlogo.gif"></td></tr>
	<tr><td align="center"><h3>TONG HSING ELECTRONICS PHILIPPINES</h3></td></tr>	
	<tr><td align="center"><h4>Administrator's Login</h4></td></tr>	
</table>
<hr>

<% if flash[:notice] %>
  <div style="border:1px solid green; width:300px;"><%=flash[:notice]%></div>
<% end %>
<% if flash[:error] %>
  <div style="border:1px solid red; width:300px;"><%=flash[:error]%></div>
<% end %>

<% form_tag :action => "index" do %>
<table>
	<tr>
	<td rowspan="3"><img src="/images/login.jpg"></td>
  <tr><td><label for="login_username">Username</label></td>
	<td><input id="login_username" name="login[username]" size="30" type="text" value="<%=@admin%>" /></td></tr>
	<tr><td><label for="login_password">Password</label></td>
	<td><input id="login_password" name="login[password]" size="30" type="password" /></td></tr>
	<tr><td colspan="2"><%= submit_tag "Login" %></td></tr>
</table>
<% end %>

</center>

app/views/admin/menu.html.erb
<ul>
  <li> <%= link_to "User Positions", ecnpositions_path %> </li>
  <li> <%= link_to "Document Categories", doc_categories_path %> </li>
  <li> <%= link_to "User List", ecnusers_path %> </li>
  <li> <%= link_to "Customer List", customer_infos_path %> </li>
</ul>