config/routes.rb
Laguna::Application.routes.draw do

  resources :doc_categories

  resources :ecnreview_forms

  resources :ecndocuments do
    member do 
      get 'print'
    end
  end

  resources :approvals

  resources :customer_infos do
    member do
      get 'get_th_pn'
      get 'get_suggestions'
    end
  end

  resources :ecnsignatures

  resources :ecnpositions

  resources :ecnusers do
    member do
      get 'edit_profile'
      put 'update_profile'
    end
  end
  
  match 'login' => "Login#index"
  match 'logout' => "Login#destroy"
  
  match 'admin/login' => "Admin#index"
  match 'admin/logout' => "Admin#destroy"
  match 'admin' => "Admin#index"

  root :to => "ecndocuments#index"

end

app/models/ecnuser.rb
class Ecnuser < ActiveRecord::Base
  require 'digest/md5'
  has_many :approvals
  has_many :ecnreview_forms, :primary_key => :id, :foreign_key => :user_id
  belongs_to :ecnposition, :primary_key => :id, :foreign_key => :pos_id
  
  before_save :hash_password
  
  has_attached_file :signature
  
  attr_accessor :password_confirmation
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true, :confirmation => true
  
  def full_name
    self.first_name + " " + self.last_name
  end
  
  def self.authenticate(username="", password="")
    user = self.where("username = :username", {:username => username} ).first
    if user
      if user.password != Digest::MD5.hexdigest(password)
        ["password is incorrect", user.username]
      else
        ["successful", user]
      end
    else
      ["username not found.", username]
    end
  end
  
  def self.authenticate_admin(username="", password="")
    user = self.where("username = :username", {:username => username} ).first
    if user
      if user.username != "admin" && user.ecnposition.position_name == "admin"
        ["user is unautorized", user.username]
      elsif user.password != Digest::MD5.hexdigest(password)
        ["password is incorrect", user.username]
      else
        ["successful", user]
      end
    else
      ["username not found.", username]
    end
  end

  
  private
  def hash_password
    self.password = Digest::MD5.hexdigest(self.password)
  end
end

app/controllers/ecnusers_controller.rb
class EcnusersController < ApplicationController

  before_filter :authenticate_admin, :except => [:edit_profile, :update_profile]
  
  def edit_profile
    @ecnuser = Ecnuser.find(@user.id)
    @ecnuser.password = ""
  end
  
  # PUT /ecnusers/1
  # PUT /ecnusers/1.xml
  def update_profile
    @ecnuser = Ecnuser.find(@user.id)
    params[:ecnuser][:username] = @ecnuser.username
    params[:ecnuser][:email] = @ecnuser.email
    
    respond_to do |format|
      if @ecnuser.update_attributes(params[:ecnuser])
        format.html { redirect_to( root_path, :notice => 'Ecnuser was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit_profile" }
        format.xml  { render :xml => @ecnuser.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  # GET /ecnusers
  # GET /ecnusers.xml
  def index
    @ecnusers = Ecnuser.paginate :page => params[:page], :order => "pos_id asc, last_name asc, first_name asc", :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ecnusers }
    end
  end

  # GET /ecnusers/1
  # GET /ecnusers/1.xml
  def show
    @ecnuser = Ecnuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ecnuser }
    end
  end

  # GET /ecnusers/new
  # GET /ecnusers/new.xml
  def new
    @ecnuser = Ecnuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ecnuser }
    end
  end

  # GET /ecnusers/1/edit
  def edit
    @ecnuser = Ecnuser.find(params[:id])
    @ecnuser.password = nil
  end

  # POST /ecnusers
  # POST /ecnusers.xml
  def create
    @ecnuser = Ecnuser.new(params[:ecnuser])

    respond_to do |format|
      if @ecnuser.save
        format.html { redirect_to(@ecnuser, :notice => 'Ecnuser was successfully created.') }
        format.xml  { render :xml => @ecnuser, :status => :created, :location => @ecnuser }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ecnuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ecnusers/1
  # PUT /ecnusers/1.xml
  def update
    @ecnuser = Ecnuser.find(params[:id])

    respond_to do |format|
      if @ecnuser.update_attributes(params[:ecnuser])
        format.html { redirect_to(@ecnuser, :notice => 'Ecnuser was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ecnuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ecnusers/1
  # DELETE /ecnusers/1.xml
  def destroy
    @ecnuser = Ecnuser.find(params[:id])
    @ecnuser.destroy

    respond_to do |format|
      format.html { redirect_to(ecnusers_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/ecnusers_helper.rb
module EcnusersHelper
end

app/views/ecnusers/_form.html.erb
<%= form_for(@ecnuser, :html => { :multipart => true }) do |f| %>
  <% if @ecnuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ecnuser.errors.count, "error") %> prohibited this ecnuser from being saved:</h2>

      <ul>
      <% @ecnuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pos_id, "Position" %><br />
    <%= f.select :pos_id, Ecnposition.position_for_select, :selected => @ecnuser.pos_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
   <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :signature, "Upload Signature" %><br />
    <%= f.file_field :signature %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ecnusers/edit.html.erb
<h1>Edit User:</h1>

<%= render 'form' %>
| <%= link_to 'Cancel', ecnusers_path %>

app/views/ecnusers/edit_profile.erb
<h1>Update Profile</h1>

<%= form_for(@ecnuser, :url => update_profile_ecnuser_path(@ecnuser), :html => { :multipart => true }) do |f| %>
  <% if @ecnuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ecnuser.errors.count, "error") %> prohibited this ecnuser from being saved:</h2>

      <ul>
      <% @ecnuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
 
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :disabled => true  %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :signature, "Upload Signature" %><br />
    <%= f.file_field :signature %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Cancel', root_path %>

app/views/ecnusers/index.html.erb
<h1>ECN Users</h1>

<%= link_to "New User", new_ecnuser_path %>
<br/>
<table width="100%" border="1" cellspacing="0" cellpadding="2" bordercolor="#000000" class="myTable">
  <tr>
    <th class="table_head">First Name</th>
    <th class="table_head">Last Name</th>
    <th class="table_head">Position</th>
    <th class="table_head">Username</th>
    <th class="table_head">Email</th>
    <th class="table_head" colspan="3"></th>
  </tr>
  
<% @ecnusers.each do |ecnuser| %>
  <tr>
    <td><%=ecnuser.first_name%>&nbsp;</td>
    <td><%=ecnuser.last_name %>&nbsp;</td>
    <td><%=ecnuser.ecnposition.position_name %>&nbsp;</td>
    <td><%=ecnuser.username %>&nbsp;</td>
    <td><%=ecnuser.email %>&nbsp;</td>
    <td><%= link_to "Show", ecnuser %></td>
    <td><%= link_to "Edit", edit_ecnuser_path(ecnuser) %></td>	
    <td><%= link_to "Delete", ecnuser, :confirm => "Are you sure?", :method => :delete, :class => "red"  %></td>
  </tr>
<% end %>
</table>
<br/>
<%= link_to "New User", new_ecnuser_path %>
<br/>
<div style="text-align:center">
<%= will_paginate @ecnpositions %>
</div>

app/views/ecnusers/new.html.erb
<h1>New User</h1>

<%= render 'form' %>
| <%= link_to 'Cancel', ecnusers_path %>

app/views/ecnusers/show.html.erb
<div style="float:left; display:inline-block; width:400px;">
<p><b>First Name</b>: <%=@ecnuser.first_name %></p>
<p><b>Last Name</b>: <%=@ecnuser.last_name %></p>
<p><b>Position</b>: <%=@ecnuser.ecnposition.position_name %></p>
<p><b>Username</b>: <%=@ecnuser.username %></p>
<p><b>Email</b>: <%=@ecnuser.email %></p>
</div>
<div>
<% if @ecnuser.signature.exists? then %>
	<%= image_tag @ecnuser.signature.url %>
<% end %>
</div>
<div style="clear:both"></div>
<%= link_to 'Back', ecnusers_path %>