config/routes.rb
Laguna::Application.routes.draw do

  resources :doc_categories

  resources :ecnreview_forms

  resources :ecndocuments do
    member do 
      get 'print'
    end
  end

  resources :approvals

  resources :customer_infos do
    member do
      get 'get_th_pn'
      get 'get_suggestions'
    end
  end

  resources :ecnsignatures

  resources :ecnpositions

  resources :ecnusers do
    member do
      get 'edit_profile'
      put 'update_profile'
    end
  end
  
  match 'login' => "Login#index"
  match 'logout' => "Login#destroy"
  
  match 'admin/login' => "Admin#index"
  match 'admin/logout' => "Admin#destroy"
  match 'admin' => "Admin#index"

  root :to => "ecndocuments#index"

end

app/views/layouts/_footer.html.erb
<div style="clear:both;"></div><br><br><br>
<hr>
<center>&copy; 2008 Tonghsing Electronics Philippines</center>

app/views/layouts/_navi.html.erb
<div style="float:left;width:100%">
<div style="width:130px;float:left"><img src="/images/thlogo.gif"></div>
<div style="width:49%;float:left;"><br><br><p class="banner">TONG HSING ELECTRONICS (PHILS.), INC.</p><br></div> 
<div style="width:36%;float:right;right:1;align:right;"><img src="/images/right_banner.jpg"></div>
</div>
<div style="float:right;right:1;align:right;width:100%">
	<div style="width:50%;float:left"><br>
  <% if @admin %>
	Welcome, <b><%=@admin.first_name%></b>
  <% else %>
	Welcome, <b><%=@user.first_name%></b>
  <% end %>
	</div>
	<% if @user && @user.pos_id == ORIGINATOR_ACCESS %>
	<div style="width:32%;float:right;right:1;align:right;">
	<% else %>
	<div style="width:22%;float:right;right:1;align:right;">
	<% end %>
	<table border="0">
  <% if @admin %>
	<tr align="center">
    <td><%=link_to image_tag("/images/home.jpg"), admin_path %></td>
    <td><%=link_to image_tag("/images/user_icon.jpg"), ecnusers_path %></td>
    <td><%=link_to image_tag("/images/add.png"), customer_infos_path %></td>
    <td><%=link_to image_tag("/images/off.jpg"), admin_logout_path %></td>
  </tr>
  <tr align="center">
		<td class="tdhead">Home</td>
		<td class="tdhead">User Admin</td>
    <td class="tdhead">&nbsp;&nbsp;Customer ID/TH PN&nbsp;&nbsp;</td>
		<td class="tdhead">Logout</td>	
	</tr>
  <% else %>  
	<tr align="center">
    <td><%=link_to image_tag("/images/home.jpg"), root_path %></td>
    <td><%=link_to image_tag("/images/user_icon.jpg"), edit_profile_ecnuser_path(@user.id) %></td>
		<% if @user && @user.pos_id == ORIGINATOR_ACCESS %>
			<td><a href="/ecndocuments/new"><img src="/images/new.jpg" alt="new" width="45px"></a></td>
		<% end %>
		<% if @user && @user.pos_id != 9 %>
		<td><a href="/ecndocuments/search"><img src="/images/find.jpg" width="45px"></a></td>
		<% end %>
		<td><a href="http://apps.tonghsing.ph/ecn/"><img src="/images/chart.jpg" width="45px"></a></td>
		<td><a href="/logout"><img src="/images/off.jpg" width="45px"></a></td>
	</tr>
  <tr align="center">
		<td class="tdhead">Home</td>
		<td class="tdhead">Profile</td>
		<% if @user && @user.pos_id == ORIGINATOR_ACCESS %>		
		<td class="tdhead">&nbsp;&nbsp;New ECN Doc&nbsp;&nbsp;</td>
		<% end %>
		<% if @user && @user.pos_id != 9 %>
		<td class="tdhead">&nbsp;&nbsp;Find ECN Doc&nbsp;&nbsp;</td>
		<% end %>
		<td class="tdhead" align="center">Status Report</td>
		<td class="tdhead">Logout</td>	
	</tr>
  <% end %>
	
	</table>
	</div>
</div>
<div style="clear:both;"></div>
<div style="width:100%; background-color:darkgray;">
<div style="margin:20px;">
<% if @admin %>
<%= link_to "Home", admin_path, :style => "color:white" %>
<% else %>
<%= link_to "Home", root_path, :style => "color:white" %>
<% end %>
</div>
</div>
<div style="clear:both;"></div>

app/views/layouts/_navi_admin.html.erb
<div style="float:left;width:100%">
<div style="width:130px;float:left"><img src="/images/thlogo.gif"></div>
<div style="width:49%;float:left;"><br><br><p class="banner">TONG HSING ELECTRONICS (PHILS.), INC.</p><br></div> 
<div style="width:36%;float:right;right:1;align:right;"><img src="/images/right_banner.jpg"></div>
</div>
<div style="float:right;right:1;align:right;width:100%">
	<div style="width:20%;float:left"><br>
	Welcome, <b><%=@admin.first_name%></b>
	</div>
	<div style="float:right;right:1;align:right;">
  <div id="menu">
    <div>
      <%=link_to image_tag("/images/home.jpg"), admin_path %> <br/>
      Home
    </div>
    <div>
      <%=link_to image_tag("/images/user_icon.jpg"), ecnusers_path %> <br/>
      User Admin
    </div>
    <%= report_menu %>
    <div>
      <%=link_to image_tag("/images/add.png"), customer_infos_path %> <br/>
      Customer ID/TH PN
    </div>
    <div>
      <%=link_to image_tag("/images/off.jpg"), admin_logout_path %> <br/>
      Logout
    </div>
  </div>
	</div>
</div>
<div style="clear:both;"></div>
<div style="width:100%; background-color:darkgray;">
<div style="margin:20px;">
<%= link_to "Home", admin_path, :style => "color:white" %>
</div>
</div>
<div style="clear:both;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= "TONGHSING Electronics Philippines Inc." if @pagetitle.nil? || @pagetitle.blank? %><%= @pagetitle%></title>
  <%= stylesheet_link_tag :all %>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <%= javascript_include_tag "jquery-1.4.4.min", "rails.1.4.4", "application", "jquery.autocomplete" %>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  
  <%= csrf_meta_tag %>
  <style type="text/css">
    .red { 
      color: red; 
    }
    .actions{
      float:left;
    }
    
    .myTable {
      width:100%;
    }
    .myTable tr:hover td{
      background-color: lightgray;
    }
    
    body { font-family: Arial; }
    td { vertical-align: top; }
    img { border-style:none; }
    a:hover { text-decoration:none; }
    a:link { text-decoration:none; }
    a:visited { text-decoration:none; }	
    .table_head { background-color:#0099CC; color:#FFFFFF; }
    .banner { font-size: 20px; color:#003399; font-weight:bold;}	
    .tdhead { font-size: 12px; }
  </style>
</head>
<body>
<% if @admin %>
<%=render :partial => "layouts/navi_admin" %>
<% else %>
<%=render :partial => "layouts/navi" %>
<% end %>

<%= yield  %>

<%=render :partial => "layouts/footer" %>
</body>
</html>