config/routes.rb
Laguna::Application.routes.draw do

  resources :doc_categories

  resources :ecnreview_forms

  resources :ecndocuments do
    member do 
      get 'print'
    end
  end

  resources :approvals

  resources :customer_infos do
    member do
      get 'get_th_pn'
      get 'get_suggestions'
    end
  end

  resources :ecnsignatures

  resources :ecnpositions

  resources :ecnusers do
    member do
      get 'edit_profile'
      put 'update_profile'
    end
  end
  
  match 'login' => "Login#index"
  match 'logout' => "Login#destroy"
  
  match 'admin/login' => "Admin#index"
  match 'admin/logout' => "Admin#destroy"
  match 'admin' => "Admin#index"

  root :to => "ecndocuments#index"

end

app/models/doc_category.rb
class DocCategory < ActiveRecord::Base
  has_and_belongs_to_many :ecnpositions, :uniq => :true, :order => "ecnposition_id asc"
  has_many :ecndocuments
end

app/controllers/doc_categories_controller.rb
class DocCategoriesController < ApplicationController
  
  before_filter :authenticate_admin
  
  # GET /doc_categories
  # GET /doc_categories.xml
  def index
    @doc_categories = DocCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @doc_categories }
    end
  end

  # GET /doc_categories/1
  # GET /doc_categories/1.xml
  def show
    @doc_category = DocCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @doc_category }
    end
  end

  # GET /doc_categories/new
  # GET /doc_categories/new.xml
  def new
    @doc_category = DocCategory.new
    @ecnpositions = Ecnposition.order("id asc")
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @doc_category }
    end
  end

  # GET /doc_categories/1/edit
  def edit
    @doc_category = DocCategory.find(params[:id])
    @ecnpositions = Ecnposition.order("id asc")
  end

  # POST /doc_categories
  # POST /doc_categories.xml
  def create
    @doc_category = DocCategory.new(params[:doc_category])

    respond_to do |format|
      if @doc_category.save
        format.html { redirect_to(@doc_category, :notice => 'Doc category was successfully created.') }
        format.xml  { render :xml => @doc_category, :status => :created, :location => @doc_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @doc_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /doc_categories/1
  # PUT /doc_categories/1.xml
  def update
    @doc_category = DocCategory.find(params[:id])

    respond_to do |format|
      if @doc_category.update_attributes(params[:doc_category])
        format.html { redirect_to(@doc_category, :notice => 'Doc category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @doc_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /doc_categories/1
  # DELETE /doc_categories/1.xml
  def destroy
    @doc_category = DocCategory.find(params[:id])
    @doc_category.destroy

    respond_to do |format|
      format.html { redirect_to(doc_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/doc_categories_helper.rb
module DocCategoriesHelper
end

app/views/doc_categories/_form.html.erb
<%= form_for(@doc_category) do |f| %>
  <% if @doc_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc_category.errors.count, "error") %> prohibited this doc_category from being saved:</h2>

      <ul>
      <% @doc_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :alias %><br />
    <%= f.text_field :alias %>
  </div>
  <ul style="list-style:none">
  <% for position in @ecnpositions %>
    <li>
      <label>
        <%=check_box_tag "doc_category[ecnposition_ids][]", position.id,  @doc_category.ecnpositions.include?(position)%>
        <span><%=position.position_name%></span>
      </label>
    </li>
  <% end %>
  </ul>
  <div style="clear:both"></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doc_categories/edit.html.erb
<h1>Edit Document Category:</h1>

<%= render 'form' %>

| <%= link_to 'Cancel', doc_categories_path %>

app/views/doc_categories/index.html.erb
<h1>Document Categories</h1>

<%= link_to "New Document Category", new_doc_category_path %>
<br/>
<table width="100%" border="1" cellspacing="0" cellpadding="2" bordercolor="#000000" class="myTable">
  <tr>
    <th class="table_head">Name</th>
    <th class="table_head">Alias</th>
    <th class="table_head" colspan="3"></th>
  </tr>

<% @doc_categories.each do |doc_category| %>
  <tr>
    <td><%= doc_category.name %></td>
    <td><%= doc_category.alias %></td>
    <td><%= link_to "Show", doc_category %></td>
    <td><%= link_to "Edit", edit_doc_category_path(doc_category) %></td>
    <td><%= link_to "Delete", doc_category, :confirm => "Are you sure?", :method => :delete, :class => "red"  %></td>
  </tr>
<% end %>
</table>

<br/>
<%= link_to "New Document Category", new_doc_category_path %>

app/views/doc_categories/new.html.erb
<h1>New Document Category</h1>

<%= render 'form' %>
| <%= link_to 'Cancel', doc_categories_path %>

app/views/doc_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @doc_category.name %>
</p>

<p>
  <b>Alias:</b>
  <%= @doc_category.alias %>
</p>

<p>
For Approval, Action, Items, Concerns, Comments, Disposition
</p>
<ol>
<% for position in @doc_category.ecnpositions %>
  <li><%=position.position_name%></li>
<% end %>
</ol>
<div style="clear:both"></div>
<%= link_to "Back", doc_categories_path %>